# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b385bb6127b4b93ca6359d00a56075d45958f02dbbb4170d5bb0856dff17e67584c1a04de10cfca4a0244235e7ea08e56fbdd18e7eb3a759830577716009376

test:
  secret_key_base: feef4c8c9e1e177001411b9894d72bf2e1944f1fa26e61225b7f11441ec4a5a83efbdd3c8c8075d0368bcb88a890386653b9ca73ba1adceeac2fb88436546782

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
